classapp/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'classapp/home.html'}),
    url(r'^accounts/logout/$', 'classapp.views.logout_view'),
    url(r'^accounts/profile/$', 'classapp.views.course_list_view'),
    url(r'^accounts/edit/$', 'classapp.views.info_edit_view'),
    url(r'^courses/list/$', 'classapp.views.course_list_view'),
    url(r'^courses/add/$', 'classapp.views.course_add_view'),
    url(r'^courses/view/(?P<courseid>\d+)$', 'classapp.views.course_view_view'),
    url(r'^courses/leave/(?P<courseid>\d+)$', 'classapp.views.course_leave_view'),
    url(r'^postreply/(?P<postid>\d+)$', 'classapp.views.post_reply_view'),
    url(r'^courses/classmates/(?P<courseid>\d+)$', 'classapp.views.classmate_view'),
    url(r'^noprofessors/$', 'classapp.views.no_professors_view'),
    url(r'^$', 'classapp.views.home_view')
)

codathon2015/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'codathon2015.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('classapp.urls')),
)

classapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager

class UVMUserManager(BaseUserManager):
    def _create_user(self, netid, password, first_name=None, last_name=None, uvm_email=None, full_name=None, department=None):
        if not netid:
            raise ValueError("Netid must be set")

        user = self.model(netid=netid, first_name=first_name, last_name=last_name, full_name=full_name, department=department)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, netid, password=None, **extra_fields):
        return self._create_user(netid,password, **extra_fields)

    def create_superuser(self, netid, password=None, **extra_fields):
        return self._create_user(netid, password, **extra_fields)

class UVMUser(AbstractBaseUser):
    """A custom user model to represent a UVM student."""
    netid = models.CharField(max_length=8,unique=True)
    first_name = models.CharField(max_length=40,null=True)
    last_name = models.CharField(max_length=40,null=True)
    uvm_email = models.CharField(max_length=40,null=True)
    full_name = models.CharField(max_length=150,null=True)
    department = models.CharField(max_length=40,null=True)

    facebook_url = models.CharField(max_length=100, null=True)
    additional_email_1 = models.CharField(max_length=100, null=True)
    additional_email_2 = models.CharField(max_length=100, null=True)
    phone_number = models.CharField(max_length=14, null=True)
    #user_picture goes here later

    USERNAME_FIELD = 'netid'
    objects = UVMUserManager()

class Course(models.Model):
    """Represents a course at UVM."""
    term = models.CharField(max_length=40)
    subject = models.CharField(max_length=10)
    number = models.IntegerField()
    crn = models.IntegerField()
    section = models.CharField(max_length=2)
    instructor = models.TextField()
    name = models.CharField(max_length=150,null=True)
    description = models.CharField(max_length=500,null=True)

    users = models.ManyToManyField("UVMUser")


    def get_absolute_url(self):
        """Returns a link to a page where the course can be viewed."""
        return "/courses/view/" + str(self.id)

class Post(models.Model):
    """Represents a post to a course."""
    user = models.ForeignKey("UVMUser")
    course = models.ForeignKey("Course")
    content = models.TextField()
    time = models.DateTimeField(auto_now=True)

    anon = models.BooleanField(default=False)

class Comment(models.Model):
    """Represents a comment on a post to a course."""
    user = models.ForeignKey("UVMUser")
    post = models.ForeignKey("Post")
    content = models.TextField()
    time = models.DateTimeField(auto_now=True)

    anon = models.BooleanField(default=False)

classapp/forms.py
from django import forms
from django.forms import ModelForm
from classapp.models import *
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import urllib
import json

class ContactForm(ModelForm):
    
    facebook_url = forms.CharField(required=False)
    additional_email_1 = forms.CharField(required=False)
    additional_email_2 = forms.CharField(required=False)
    phone_number = forms.CharField(required=False)
    
    class Meta:
        model = UVMUser
        fields = ['facebook_url', 'additional_email_1','additional_email_2','phone_number']

class AddCourseForm(forms.Form):
    def getTermChoices(): # Because of how this is called below, don't add a self argument..

        url = "https://www.uvm.edu/_api.d/v1/course-catalogue/terms"
        response = urllib.urlopen(url)
        data = json.loads(response.read())

        choices = ()
        for term in data[u'terms']:
            choices += ( (term[u'code'], term[u'name']), )

        return choices

    def clean(self):
        cleaned_data = super(AddCourseForm, self).clean()
        crn_good = False
        subject_good = False
        number_good = False
        section_good = False

        if u'crn' in cleaned_data.keys():
            crn_good = not cleaned_data[u'crn'] is None
        if u'subject' in cleaned_data.keys():
            subject_good = not cleaned_data[u'subject'] is None
        if u'number' in cleaned_data.keys():
            number_good = not cleaned_data[u'number'] is None
        if u'section' in cleaned_data.keys():
            section_good = not cleaned_data[u'section'] is None

        if subject_good:
            cleaned_data[u'subject'] = cleaned_data[u'subject'].upper()

        if section_good:
            cleaned_data[u'section'] = cleaned_data[u'section'].upper()

        if not (crn_good or (subject_good and section_good)):
            raise forms.ValidationError("Fill in either the CRN or the Subject/Section fields!")

        return cleaned_data


    term = forms.ChoiceField(choices=getTermChoices())
    # Either CRN
    crn = forms.IntegerField(required=False)
    # Or subject, number, section
    subject = forms.CharField(required=False)
    number = forms.IntegerField(required=False)
    section = forms.CharField(required=False)







class NewPostForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea,label="Post to the class")
    anon = forms.BooleanField(required=False,label="Post anonymously")

class NewReplyForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea,label="Reply to this post")
    anon = forms.BooleanField(required=False,label="Reply anonymously")

classapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from classapp.models import *
from classapp.forms import *
import urllib, json

def home_view(request):
    """A view for / that redirects either to a login page, or to a list of courses the user is in."""
    if request.user.is_authenticated():
        return redirect("/courses/list/")
    else:
        return redirect("/accounts/login")

def logout_view(request):
    """A view for /accounts/logout that logs the user out."""
    logout(request)
    return redirect("/")

@login_required
def course_list_view(request):
    """A view to show a list of courses the user is in."""

    # Quick hack to disallow professors from logging in
    if hasattr(request.user,'ldap_user'): # If the current user is an ldap user (not a local user)
        # Loop through their affiliations
        for affiliation in request.user.ldap_user.attrs[u'edupersonaffiliation']:
            # If they're faculty, log them out and send them to the noprofessors page.
            if affiliation == u'Faculty':
                logout(request)
                return redirect("/noprofessors")

    # Grab the list of courses for this user, and render the template.
    courses = request.user.course_set.all()
    return render(request,"classapp/courselist.html",{"courses": courses})

@login_required
def course_add_view(request):
    """A view to allow the user to add a course to their profile."""
    form = AddCourseForm(data=request.POST)
    if form.is_valid(): # This form will only validate if we either have one of: (crn) or (subject, number, section) as well as term.
        url = ""
        using_crn = not form.cleaned_data['crn'] is None # If we have a crn, use it, otherwise use subject number section.

        # Two different urls to grab the same data.
        if using_crn:
            url = "https://www.uvm.edu/_api.d/v1/course-catalogue/term/" + str(form.cleaned_data['term']) + "/crn/" + str(form.cleaned_data['crn'])
        else:
            url = "https://www.uvm.edu/_api.d/v1/course-catalogue/term/" + str(form.cleaned_data['term']) + "/subject/" + str(form.cleaned_data['subject']) + "/course/" + str(form.cleaned_data['number'])

        # Grab and decode the json from the API
        response = urllib.urlopen(url)
        data = json.loads(response.read())
        data = data[u'sections']

        # If we're not using a CRN, we were returned a list of sections. Loop through and find the right one.
        if not using_crn:
            for course in data:
                if course[u'section'] == form.cleaned_data['section']:
                    data = course
                    break # We found it, no need to keep looping.

        # Allow for multiple instructors.
        instructor_str = "N/A" # Default
        if len(data[u'instructors']) == 0:
            pass # Stick with default
        if len(data[u'instructors']) == 1:
            instructor_str = data[u'instructors'][0][u'first'] + " " + data[u'instructors'][0][u'last'] # Just one instructor.
        else: # Build a list of instructors.
            instructor_str = ""
            for instructor in data[u'instructors']:
                instructor_str += (instructor[u'first'] + " " + instructor[u'last'] + " ")

        # Grab our course - get it from the database, or create it if it doesn't exist (thanks Django)
        course,created = Course.objects.get_or_create(
                term = data[u'term_code'],
                crn = data[u'crn'],
                subject = data[u'subject'],
                number = data[u'number'],
                instructor = instructor_str,
                section = data[u'section'],
                name = data[u'crse_title'],
                description = data[u'description']
                )

        # If we had to create it, save it.
        if created:
            course.save() 
        request.user.course_set.add(course) # Assign our user to it.
        return redirect("/courses/list") # Bring the user back to the list of courses.

    else:
        # The form was invalid - meaning the user either didn't fill it out, or they filled it out with errors.
        return render(request,"classapp/addcourse.html", {"form": form})

@login_required
def course_view_view(request,courseid):
    """A view to view a course by id."""

    # We have two forms here, one to post to the course and one to reply to a post.
    post_form = NewPostForm(data=request.POST) # This form posts back to this page
    reply_form = NewReplyForm() # This one posts to a different page, don't try to grab data (it's meant for post_form if it exists)

    # Grab the course we're supposed to be viewing. 404 if it doesn't exist.
    course = get_object_or_404(Course, id=courseid)

    # If we have valid data for a post, make sure to save it BEFORE fetching data for the page, so we can see the new post immediately.
    if post_form.is_valid():
        post = Post(
                    user = request.user,
                    course = course,
                    content = post_form.cleaned_data['content'],
                    anon = post_form.cleaned_data['anon'],
                )
        post.save()

    # Grab all posts, ordered so most recent are first.
    posts = Post.objects.filter(course=course).order_by('-time')
    post_form = NewPostForm() # Clear the form, so old data doesn't stick in it when we display the page.
    return render(request, "classapp/courseview.html", {
        "course": course,
        "posts": posts,
        "new_post_form": post_form,
        "new_reply_form": reply_form
        })


@login_required
def post_reply_view(request, postid):
    """A view to save a reply to a post. Doesn't render anything, only redirects back to the course after either succeeding or failing."""
    # Grab our form and requested parent post
    form = NewReplyForm(data=request.POST)
    post = get_object_or_404(Post,id=postid)

    # If we have valid data, save our new comment.
    if form.is_valid():
        comment = Comment(
                user = request.user,
                post = post,
                content = form.cleaned_data['content'],
                anon = form.cleaned_data['anon'],
            )
        comment.save()
    # Return to the course page where we posted the reply.
    return redirect(post.course.get_absolute_url())


@login_required
def classmate_view(request,courseid):
    """A view to list all students in the class."""
    # Grab the course and all users in it, render the template.
    course = get_object_or_404(Course, id=courseid)
    users =  UVMUser.objects.filter(course=course).order_by("last_name")
    return render(request, "classapp/classmates.html",{"course": course, "users": users})

@login_required
def info_edit_view(request):
    """Returns a page that allows users to edit their information."""
    form = ContactForm(data=request.POST)

    # If we have valid data, update the current user object and save it.
    if form.is_valid():
        user = request.user
        user.facebook_url = form.cleaned_data['facebook_url']
        user.additional_email_1 = form.cleaned_data['additional_email_1']
        user.additional_email_2 = form.cleaned_data['additional_email_2']
        user.phone_number = form.cleaned_data['phone_number']

        user.save()
    # Render the same page again.
    return render(request,"classapp/info_form.html", {"form": form, "person":request.user})

def no_professors_view(request):
    """Renders a fun little "no professors allowed" page."""
    return render(request, "classapp/noprofessors.html")

@login_required
def course_leave_view(request, courseid):
    """A view to allow a user to leave a course. Only linked to, doesn't render anything, only redirects back."""
    course = get_object_or_404(Course, id=courseid)
    course.users.remove(request.user)
    return redirect("/courses/list")

classapp/templates/classapp/addcourse.html
{% extends "classapp/base.html" %}

{% block body %}
<article>
    <h2>Add a course that you're taking</h2>
    <p id="course_form">Either input course CRN number or subject, number, and section.</p>
<br>
<form id="form_input" action="/courses/add/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</article>
{% endblock %}

classapp/templates/classapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link href='{% static "screen.css" %}' media="screen, projection" rel='stylesheet' type="text/css">
</head>
<body>
    {% if user.is_authenticated %}
    <div class="main_content">
    {% endif %}
    {% block body %}
    
    
    {% endblock %}
    {% if user.is_authenticated %}
    </div>
    {% endif %}
    {% if user.is_authenticated %}
	<div class='sidebar'>
	    <div class='sidebar_info'>
	    	<img src='{% static "images/avatar_logo_default.png" %}' class='avatar_logo_default'>
	        <p class='welcome_text'>Hello, {{ user.full_name }}</p><a href="/accounts/logout" class='logout'>Logout</a>
	    </div>
	    <div class='sidebar_tools'>
		    
			<ul class='nav'>
				<li><a href="/accounts/profile/">Home</a></li>
				<li><a href="/courses/add">Add a course</a></li>
				<li><a href="/accounts/edit">Edit Personal Info</a></li>
			</ul>
			<p class="help_content2">CatLynx is a web app that connects classmates in order to collaborate, get help, and share insights.
We've all been in a class where we don't know anyone. 
CatLynx is here to make sure that even the most shy and quiet student can find help.
Since CatLynx uses UVM authentication, only current UVM students can sign in.
No professors, which means no pressure and no impact on your grades!
</p>
	    </div>
	</div>
	{% endif %}
</body>
</html>

classapp/templates/classapp/classmates.html
{% extends "classapp/base.html" %}
    {% load staticfiles %}

{% block body %}
<a href="/courses/view/{{ course.id }}" >See Class Page.</a>
    <div class='classmates'>
    {% for person in users %}

        <div class="contact_card">
        	<div class='person_name'>
        	<img src='{% static "images/avatar_logo_default.png" %}' class='card_icon'>
        	<span class='name'>{{ person.first_name }} {{ person.last_name }}</span>
        	</div>
        	
        	<div class='person_info'>
        	<ul class="contact_info_list">
        		
        		<li>
        			UVM Email: <a href="mailto:{{ person.uvm_email }}?Subject=Message from a classmate via CatLynx">{{ person.uvm_email }}</a>
        		</li>

        		{% if person.facebook_url %}
        			<li>
        				<a href="{{ person.facebook_url }}">{{ person.first_name }}'s Facebook</a>
        			</li>
        		{% endif %}

        		{% if person.additional_email_1 %}
        			<li>
        				Other Email: {{ person.additional_email_1 }}
        			</li>
        		{% endif %}

        		{% if person.additional_email_2 %}
        			<li>
        				Alternate Email: {{ person.additional_email_2 }}
        			</li>
        		{% endif %}

        		{% if person.phone_number %}
        			<li>
        				Phone: {{ person.phone_number }}
        			</li>
        		{% endif %}
        	
        	</ul>
        	</div>
        </div>

    {% endfor %}

    </div>
{% endblock %}

classapp/templates/classapp/courselist.html
{% extends "classapp/base.html" %}
{% load staticfiles %}

{% block body %}

<div class='courselist'>
		<div class='courselist_classes'>
	
	    {% for course in courses %}
			<div class='course_object'>
		    <a href="{{ course.get_absolute_url }}" class='course_id'>
		    	<p>
		    		{{ course.subject }}
	                {{ course.number }}
	                {{ course.section }}
		    	</p>
			</a>
			<div class='course_info'>
		    	<p>
                    <b><i>{{ course.name }}</i></b>
		    	</p>
		    	<p>
		    		{{ course.instructor }}
		    	</p>
                <br>
		    	<p>
		    		{{ course.description }}
		    	</p>
			</div>
                <br>
            <a href="/courses/leave/{{ course.id }}">Leave Course</a>
		</div>
	    {% endfor %}
	</div>
</div>

{% endblock %}

classapp/templates/classapp/courseview.html
{% extends "classapp/base.html" %}

{% block body %}

<article class='course_view'>
<h2>{{ course.term }} {{ course.subject }}{{ course.number }}, Section {{ course.section }}</h2>
<div class='see_classmates'>
<a href="/courses/classmates/{{ course.id }}" class='see_classmates'>See classmates.</a>
</div>

<form action="{{ course.get_absolute_url }}" method="post" class='post_form'>
    {% csrf_token %}
    {{ new_post_form }}
    <br>
    <input type="submit" value="Post">
</form>

<ul class="posts">
    {% for post in posts %}
        <li class="post">
            {% if post.anon %}
                <p>Anonymous</p>
                <p>{{ post.content }}</p>
            {% else %}
                <p>{{ post.user.full_name }}</p>
                <p>{{ post.content }}</p>
            {% endif %}

            <ul class="comments">
                {% for comment in post.comment_set.all %}
                    <li class="comment">
                        {% if comment.anon %}
                            <p>Anonymous</p>
                            <p class='comment_content'>{{ comment.content }}</p>
                        {% else %}
                            <p>{{ comment.user.full_name }}</p>
                            <p class='comment_content'>{{ comment.content }}</p>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <h5>REPLY</h5>
            <form action="/postreply/{{ post.id }}" method="post">
                {% csrf_token %}
                {{ new_reply_form }}
                <input type="submit" value="Post reply">
            </form>
        </li>
        
        <hr>

    {% endfor %}
</ul>
</article>
{% endblock %}

classapp/templates/classapp/home.html
{% extends "classapp/base.html" %}

{% block body %}

{% if request.user.is_authenticated %}
 You are logged in yay
{% else %}
{% endif %}

{% if form.errors %}
Form errors
{% endif %}
{% load staticfiles %}


<div class="login">
	<div class='home_logo main_content'>
		<img src='{% static "images/logo.png" %}' class='home_logo_image'>
	</div>
	<div class='sidebar'>
    <img src='{% static "images/title.png" %}' class='title_image'>
    <form action="/accounts/login/" method="post" class='login_form'>
        {% csrf_token %}
        <label>NetID</label>
        {{ form.username }}
        
        <label>Password</label>
        {{ form.password }}
        <input type="submit" value="login">
    </form>
    <br><br>
	    <button class='help_button'>Help (?)</button>
			<div class='help_content'><p><br>CatLynx is a web app that connects classmates in order to collaborate, get help, and share insights.
			We've all been in a class where we don't know anyone. 
			CatLynx is here to make sure that even the most shy and quiet student can find help.
			Since CatLynx uses UVM authentication, only current UVM students can sign in.
			No professors, which means no pressure and no impact on your grades!</p>
		</div>
	</div>
</div>

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
	$(document).ready(function(){
		$("p").hide();

	    $("button").click(function(){
	        $("p").toggle(200);
	    });
	});
 </script>

{% endblock %}

classapp/templates/classapp/info_form.html
{% extends "classapp/base.html" %}
{% block title %}Personal Contact Information{% endblock %}
{% block body %}

<article>
    <h2>Editing the contact info of {{ person.first_name }} {{ person.last_name }}.</h2><br>
    <form action="/accounts/edit/" method="POST">

    {% if form.non_field_errors %}
    	<div class= "alert alert-danger">
    		{{ form.non_field_errors }}
    	</div>
    {% endif %}
        
        {% csrf_token %}
        <h3>We already have your UVM email: <span style='font-style: italic;'>{{ person.uvm_email }}</span></h3>
            <br>
        <h3>Link Social Media</h3>
        <span class = "form_item" id = "facebook_url">
        	<label for="id_facebook_url">Facebook profile URL</label> 
        	{{ form.facebook_url }}
        </span>
    {% if form.facebook_url.errors %}
    	<div class = "field-error">
    		{{ form.facebook_url.errors }}
    	</div>
    {% endif %}

            <br><br>
        
        <h3>Additional email addresses to contact you at</h3>
        <span class = "form_item" id = "additional_email_1">
        	<label for="id_additional_email_1">Additional Email</label> 
        	{{ form.additional_email_1 }}
        </span>
            <br>
        <span class = "form_item" id = "additional_email_2">
        	<label for="id_additional_email_2">Additional Email</label> 
        	{{ form.additional_email_2 }}
        </span>
    {% if form.additional_email.errors %}
    	<div class = "field-error">
    		{{ form.additional_email.errors }}
    	</div>
    {% endif %}
            
            <br>
            <br>
        
        <h3>Phone</h3>
        <span class = "form_item" id = "phone_number">
            <label for="id_phone_number">Enter </label> 
            {{ form.phone_number }}
        </span>
    {% if form.phone_number.errors %}
        <div class = "field-error">
            {{ form.phone_number.errors }}
        </div>
    {% endif %}
        <br><br>
        <span class = "form_item submit_button"><input type="submit" class="btn btn-default" value="Save"></span>
    </form>
</article>

{% endblock %}

classapp/templates/classapp/loggedout.html
{% extends "classapp/base.html" %}

{% block body %}

Successfully logged out

{% endblock %}

classapp/templates/classapp/login.html
{% extends "classapp/base.html" %}

{% block body %}

{% if request.user.is_authenticated %}
 You are logged in yay
{% else %}
You are not logged in yet
{% endif %}

{% if form.errors %}
Form errors
{% endif %}


<div class="login">
    <form action="/accounts/login/" method="post">
        {% csrf_token %}
        Username
        {{ form.username }}
        Password
        {{ form.password }}
        <input type="submit" value="login">
    </form>
</div>

{% endblock %}

classapp/templates/classapp/noprofessors.html
<style>
.image {
    position: absolute;
    top: 20%;
    left: 20%;
    /*width: 120px;
    height: 120px;*/
    margin:-60px 0 0 -60px;
    -webkit-animation:spin 4s linear infinite;
    -moz-animation:spin 4s linear infinite;
    animation:spin 4s linear infinite;
}
@-moz-keyframes spin { 100% { -moz-transform: rotate(360deg); } }
@-webkit-keyframes spin { 100% { -webkit-transform: rotate(360deg); } }
@keyframes spin { 100% { -webkit-transform: rotate(360deg); transform:rotate(360deg); } }
    
    .text1{
    position: absolute;
    top: 10%;
    left: 10%;
    /*width: 120px;
    height: 120px;*/
    margin:-60px 0 0 -60px;
    -webkit-animation:spin 4s linear infinite;
    -moz-animation:spin 4s linear infinite;
    animation:spin 4s linear infinite;
}
@-moz-keyframes spin { 100% { -moz-transform: rotate(360deg); } }
@-webkit-keyframes spin { 100% { -webkit-transform: rotate(360deg); } }
@keyframes spin { 100% { -webkit-transform: rotate(360deg); transform:rotate(360deg); } }
    
    .text2{
    position: absolute;
    top: 40%;
    left: 40%;
    /*width: 120px;
    height: 120px;*/
    margin:-60px 0 0 -60px;
    -webkit-animation:spin 4s linear infinite;
    -moz-animation:spin 4s linear infinite;
    animation:spin 4s linear infinite;
}
@-moz-keyframes spin { 100% { -moz-transform: rotate(360deg); } }
@-webkit-keyframes spin { 100% { -webkit-transform: rotate(360deg); } }
@keyframes spin { 100% { -webkit-transform: rotate(360deg); transform:rotate(360deg); } }
    
    h1{
    color:red;
    }
</style>
{% extends "classapp/base.html" %}


{% block body %}
<h1>Professors not allowed!</h1>
<img src='http://i.imgur.com/TYF1fZk.png' class='image'>
<div class='text1'>
<h1>Professors not allowed!</h1>
<h1>GO AWAY BOB</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>GO AWAY BOB</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
    <div class='image'>
        <br><br>
    <h1>GO AWAY BOB</h1>
    </div>
</div>
<div class ='image'><img src ='http://2.bp.blogspot.com/-rabogZgC76s/VDUiF7_ZYZI/AAAAAAAAMss/iD0GVSuWZBk/s1600/tumblr_static_42q8mrz8qzeo4sk0kwcock8gw.gif'></div>
<div class='text2'>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>GO AWAY BOB</h1><h1>GO AWAY BOB</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>GO AWAY BOB</h1>
    <img src ='http://2.bp.blogspot.com/-rabogZgC76s/VDUiF7_ZYZI/AAAAAAAAMss/iD0GVSuWZBk/s1600/tumblr_static_42q8mrz8qzeo4sk0kwcock8gw.gif'>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
<h1>Professors not allowed!</h1>
</div>

{% endblock %}